#pragma once

#define Naked __declspec( naked ) 
#define Thread __declspec( thread )

#define masyvas array
#define automatinis auto
#define bulis bool
#define sulauzyti break
#define atvejis case
#define pagauti catch
#define raide char
#define clase class
#define pastovus const
#define pastovus_mesti const_cast
#define testi continue
#define deklaruotiTipa decltype
#define numatytas default
#define deleguoti delegate 
#define istrinti delete
#define daryti do
#define dvigubas double
#define naturalusis64 double
#define dinaminis_mesti dynamic_cast
#define kitas else
#define skaitiklis enum
#define ivykis event
#define aiskus explicit
#define isorinis extern
#define netiesa false
#define pagaliau finally
#define naturalusis float
#define naturalusis32 float
#define del for
#define kiekvienam for each
#define is in
#define draugas friend
#define gcnaujas gcnew
#define bendrinis generic
#define eiti_i goto
#define jei if
#define tik_inicializuoti initonly
#define eiluteje inline
#define naturalusis int
#define sasaja interface
#define vidaus_rodiklis interior_ptr
#define pazodziui literal
#define ilgas long
#define keiciamas mutable
#define nuogas Naked
#define vardo_vieta namespace
#define naujas new
#define nulio_rodykle nullptr
#define operatorius operator
#define privatus private
#define nuosavybe property
#define apsaugotas protected
#define viesas public
#define registruotis register
#define reinterpretuoti_mesti reinterpret_cast
#define grazinti return
//#define saugus_metimas safecast
#define uzdarytas sealed
#define trumpas short
#define pasirasytas signed
#define dydis sizeof
#define statinis static
#define statinis_teigti static_assert
#define statinis_mesti static_cast
#define struktura struct
#define perjungti switch
#define sablonas template
#define sis this
#define siulas Thread
#define mesti throw
#define tiesa true
#define bandyti try
#define tipo_aprasas typedef
#define tipo_numeris typeid
#define tipo_vardas typename
#define sajunga union
#define nepasirasytas unsigned
#define naudojant using
#define virtualus virtual
#define niekinis void
#define nepastovus volatile
#define kol while