#pragma once

#define lygiuotikaip alignas
#define lygiuoti alignof
#define ir and
#define ir_lygu and_eq
#define suringkimas asm
#define automatiskai auto
#define siek_tiek_ir bitand
#define siek_tiek_arba bitor
#define loginis bool
#define sulauzyti break
#define atvejis case
#define sugauti catch
#define simbolis char
#define simbolis8_t char8_t 
#define simbolis16_t char16_t
#define simbolis32_t char32_t
#define klase class
#define komplimentas compl
#define koncepcija concept
#define pastovus const
#define nuolatinis_vertinimas consteval 
#define nuolatine_israiska constexpr 
#define nuilatinis_inicijavimas constinit 
#define pastovus_metimas const_cast
#define testi continue
#define rutina_laukti co_await
#define rutina_grazinti co_return
#define rutina_derlius co_yield
#define deklaracijos_tipas decltype
#define numatytas default
#define istrinti delete
#define daryti do
#define dvigubas double
#define dinaminis_perdavimas dynamic_cast
#define arba else
#define surasinetojas enum
#define aiskus explicit
#define eksportuoti export
#define isorinis extern
#define klaidinga false
#define pludefloat
#define del for
#define draugas friend
#define eiti_i goto
#define jeigu if
#define eilute inline
#define sveikasis_skaicius int
#define ilgas long
#define kintamas mutable
#define vardu_erdve namespace
#define naujas new
#define jokiu_isimciu noexcept
#define ne not
#define nelygu not_eq
#define nuline_rodykle nullptr
#define operatorius operator
#define arba or
#define arba_lygu or_eq
#define privatus private
#define apsaugotas protected
#define viesas public
#define registruoti register
#define is_naujo_interpretuoti_perdavimas reinterpret_cast
#define reikalauja requires
#define grazinti return
#define trumpas short
#define pasirasytas signed
#define dydis sizeof
#define statinis static
#define statinis_teigimas static_assert
#define statinis_perdavimas static_cast
#define struktura struct
#define jungiklis switch
#define sablonas template
#define tai this
#define siulas_vietinis thread_local
#define mesti throw
#define tiesa true
#define bandyti try
#define tipo_apibrezimas typedef
#define tipi_id typeid
#define tipo_pavadinimas typename
#define sajunga union
#define nepasirasytas unsigned
#define naudojant using
#define virtualus virtual
#define tustuma void
#define nepastovios volatile
#define platus_simbolis_t wchar_t
#define kol while
#define isskirtinis_arba xor
#define isskirtinis_arba_lygu xor_eq